spring.application.name=stock-market
server.port=${PORT}
spring.datasource.url=jdbc:${DB_URL}
spring.datasource.username=${DB_UN}
spring.datasource.password=${DB_PWD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.validation.mode=none

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

stock.api.key=${STOCK_KEY}

razor-pay.api.key=${RAZOR_KEY}
razor-pay.api.secret=${RAZOR_SECRET}

platformPercentage=0.04

server.servlet.session.tracking-modes=cookie